name: Cypress Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
      timeout-minutes: 60
      runs-on: ubuntu-latest
      container: cypress/browsers
      environment: .env

      steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          
      - name: Create .env file
        run: |
          echo "ENABLE_SCREENSHOTS=${{ vars.ENABLE_SCREENSHOTS }}" >> .env
          echo "USER_PASSWORD=${{ secrets.USER_PASSWORD }}" >> .env

      - name: Install dependencies
        run: yarn install --frozen-lockfile --network-concurrency 1

      - name: Run tests
        run: yarn cypress:run

      - uses: actions/upload-artifact@v4
        if: ${{ env.ACT != 'true' && !cancelled() }}
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 30

      - uses: actions/upload-artifact@v4
        if: ${{ env.ACT != 'true' && !cancelled() }}
        with:
          name: cypress-videos
          path: cypress/videos
          retention-days: 30

      - uses: actions/upload-artifact@v4
        if: ${{ env.ACT != 'true' && !cancelled() }}
        with:
          name: cypress-reports
          path: cypress/reports
          retention-days: 30